server:
  port: 8082
  servlet:
    context-path: /DBStaging

spring:
#  datasource:
#    controller:
#      url: jdbc:postgresql://localhost:5432/DBController
#      driverClassName: org.postgresql.Driver
#      username: user
#      password: password
  controller:
    url: jdbc:postgresql://dbcontroller:5432/DBController
    username: user
    password: password
    staging:
      url: jdbc:postgresql://staging:5432/DBStaging
      username: user
      password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: trungkien19203@gmail.com
    password: neio gqvh btph nqsw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
