server:
  port: 8082
  servlet:
    context-path: /DBStaging

spring:
  datasource:
    controller:
      url: jdbc:postgresql://localhost:5454/DBController
      driverClassName: org.postgresql.Driver
      username: user
      password: password
    staging:
    url: jdbc:postgresql://localhost:5455/DBStaging
    driverClassName: org.postgresql.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
