server:
  port: 8082
  servlet:
    context-path: /DBStaging

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DBStaging
    driverClassName: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true