services:
  postgres:
    image: 'postgres:14-alpine3.20'
    environment:
      - 'POSTGRES_DB=DBController'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5454:5432'
    volumes:
      - controller_data:/var/lib/postgresql/data
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  controller_data: