services:
  controller:
    image: "postgres:14-alpine3.20"
    environment:
      - "POSTGRES_DB=DBController"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=user"
    ports:
      - "5454:5432"

  staging:
    image: "postgres:14-alpine3.20"
    environment:
      - "POSTGRES_DB=DBStaging"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=user"
    ports:
      - "5455:5432"
    depends_on:
      - controller
