services:
  controller:
    image: "postgres:14-alpine3.20"
    environment:
      - "POSTGRES_DB=DBController"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=user"
    ports:
      - "5454:5432"
    networks:
      - shared_network

  staging:
    image: "postgres:14-alpine3.20"
    environment:
      - "POSTGRES_DB=DBStaging"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=user"
    ports:
      - "5455:5432"
    networks:
      - shared_network
    depends_on:
      - controller

networks:
  shared_network: 
    external: true
