server:
  port: 8081
  servlet:
    context-path: /DBController

spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/DBController
    driverClassName: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true